### ISSUE TITLE
Deprecate CSSDeclaration.setProperty(String), use enum instead

### ISSUE THREAD

**Issue by DanielYWoo** [phax/ph-css#45]
Currently, a string property "m_sProperty" is used, can we switch to ECSSProperty? That will make the client code much easier and tidier.

E,g. 

```
new DefaultCSSVisitor() {
   @Override public void onDeclaration(@Nonnull CSSDeclaration declaration) {
        // currently:
        if (declaration.getProperty().equals("font") { ... }
        // prefer enum:
        if (declaration.getPropName() == ECSSProperty.FONT) { ...}
    }
};
```

**Comment by phax** [comment]
The problem is: there are so many CSS declarations from so many CSS "sub projects" that it is really hard to keep track of all of them. Everything contained in `ECSSProperty` is just a "temporary snapshot".
But what I **could** do is the following:
```java
if (declaration.hasProperty (ECSSProperty.FONT))
{ ... }
```
would that help. That allows you to use the enum where it fits, and allows you to use other properties, not contained in the enum as well???

**Comment by DanielYWoo** [comment]
It makes sense if you want to support more CSS declarations, even draft version.
If so, maybe it is not worthy of adding a new method, it's not a big deal to compare Strings in my case.

**Comment by DanielYWoo** [comment]
Thanks

**Comment by phax** [comment]
I anyway added a common `hasProperty` method because I think the case insensitivity helps anyway!
