### ISSUE TITLE
URI Traversing misses uris within double quote marks

### ISSUE THREAD

**Issue by Kvizer** [phax/ph-css#60]
Example CSS:

`.tp-transparentimg { content: "url(../assets/transparent.png)"; }
`

I would expect that WikiVisitUrls.java example will print url, but it does not. 

If you remove double quote marks from css, the WikiVisitUrls example works fine!

**Comment by phax** [comment]
Well, that is an issue, because if it is a String, than the parser treats it as a String. If I remove the quotes it is still a String I would need to parse separately.
You basically need to create a preprocessor that removes the superfluous quotes, and than parse it. But adding this non -standard behaviour to the core does not make sense to me...

**Comment by Kvizer** [comment]
according "CSS content Property" example from   [https://www.w3schools.com/cssref/pr_gen_content.asp](w3schools)

we can have css like

`a::after {
  content: " (" attr(href) ")";
}`

so i guess it's common behavior that someone insert url in double quote marks

**Comment by Kvizer** [comment]
Thanks for helping me clear my "css example", I appreciate your time.

**Comment by phax** [comment]
You have quite a big fan base ;-)

If you change your code to

```css
a::after { content: " (" url(/whatever.png) ")"; }
```

than it is already returned in the visitor. That is imho the same as #59 fixed for the v6.2.3 release.
Please confirm.

**Comment by phax** [comment]
Seems to work :) If not, feel free to re-open
